apiVersion: v1
kind: Service
metadata:
  name: pen-and-paper-dm-helper-service
spec:
  selector:
    app: pen-and-paper-dm-helper
    role: backend
  ports:
    - protocol: TCP
      port: 8080
  type: NodePort
  