version: '3.8'

services:
  dm-helper:
    image: xome42/pen-and-paper-dm-helper-backend-spring-postgres
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    environment:
      DB_URL: ${DB_URL}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
  db:
    image: xome42/pen-and-paper-dm-helper-db
    expose:
      - "${DB_PORT}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_NAME}
      PGPORT: ${DB_PORT}
    volumes:
      - ${PATH_TO_DB}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER} -h ${DB_URL}" ]
      interval: 3s
      timeout: 2s
      retries: 50