version: '3.8'

services:
  dm-helper:
    image: xome42/pen-and-paper-dm-helper-backend-spring-postgres
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dmhelper
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: dmhelper
    volumes:
      - ${PATH_TO_DB}:/var/lib/postgresql/data
      - ./src/main/resources/ddl.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d dmhelper -U dmhelper" ]
      interval: 3s
      timeout: 2s
      retries: 5