name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: xome42/pen-and-paper-dm-helper-backend-spring-postgres
  IMAGE_NAME_DB: xome42/pen-and-paper-dm-helper-db


jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_ACCOUNTNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name : use Maven to build jar
        id: build
        run: mvn -B --file pom.xml package
      - name: Surefire Report
        if: success() || failure()
        uses: ScaCap/action-surefire-report@v1.7.0
      - name: build app Docker image
        run: docker build . -f Dockerfile -t ${{ env.IMAGE_NAME }}
      - name: build db Docker image
        run: docker build . -f DockerfileDatabase -t ${{ env.IMAGE_NAME_DB }}
      - name: push app image to Docker Hub
        run: docker push ${{ env.IMAGE_NAME }}
      - name: push db image to Docker Hub
        run: docker push ${{ env.IMAGE_NAME_DB }}
